### ISSUE TITLE
How to setup and use the package?

### ISSUE THREAD

**Issue by yasir-naseer** [be-n-dev/laravel-lexoffice-api#1]
hi, greetings, may i know if i can find a documentation about how the package works and helps me create invoices and things like, i cant find installation docs or any guidelines thanks

**Comment by benkimdev** [comment]
Hello Yasir, 
unfortunately the package has been developed mainly for your own use, so there is no documentation.

Furthermore, I would advise you not to use this package as it is no longer developed/maintained. Sorry! 
But I would recommend you to have a look here: 

[https://github.com/Baebeca-Solutions/lexoffice-php-api/blob/master/lexoffice-php-api.php](https://github.com/Baebeca-Solutions/lexoffice-php-api/blob/master/lexoffice-php-api.php)

My package is based on the script from Baebeca-Solutions. 

Kind regards
